menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'gallery', url: '/bresearch'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}


gallery:
- {name: 'street sketch',image: 'assets/img/photo1.jpg',soundtrack: 'Clandestina',author: 'Emma Peterson',spotifyurl: 'https://open.spotify.com/track/2gRLsIZ7iYYbGVpIYK5idR?si=86b36bb6b03f4091' }
- {name: 'dialogue with a drunk man',image: 'assets/img/photo2.jpg',soundtrack: 'Corps',author: 'Yseult',spotifyurl: 'https://open.spotify.com/track/7qx03NsIL42jM03zFphnRO?si=0111e91490b04a45' }
- {name: 'Girl with yellow eyes',image: 'assets/img/photo3.jpg',soundtrack: 'This is a Men''s,Men''s,Men''s World',author: 'James Brown',spotifyurl: 'https://open.spotify.com/track/5vMTfupz6z7wlNiz0xVb4j?si=9e3b8e0bffee45e0' }
- {name: 'Untitled',image: 'assets/img/photo4.jpg',soundtrack: 'Move with you',author: 'Jacob Banks',spotifyurl: 'https://open.spotify.com/track/4VbvGwV24TbFIULF176HXF?si=19a52a10aa5a4624' }
- {name: 'Write your Personal Space',image: 'assets/img/photo5.jpg',soundtrack: 'Ora',author: 'Jovanotti',spotifyurl: 'https://open.spotify.com/track/7a7SGyZdPHY11l71HYvLlP?si=a79d106573734ed1' }
- {name: 'Kurtosis',image: 'assets/img/photo6.jpg',soundtrack: 'Just the two of us',author: 'Griver Washingthon, Bill Wither',spotifyurl: 'https://open.spotify.com/track/2tH28YyKYOldxhuBHoI79M?si=89f82606d140435b' }
- {name: 'Delft, Last Days',image: 'assets/img/photo7.jpg',soundtrack: 'Nuvole Bianche',author: 'Ludovico Einaudi',spotifyurl: 'https://open.spotify.com/track/3weNRklVDqb4Rr5MhKBR3D?si=83d883118fe1427c' }
- {name: 'Binary Love',image: 'assets/img/photo8.jpg',soundtrack: 'Scars to your Beautiful',author: 'Alessia Cara',spotifyurl: 'https://open.spotify.com/track/42ydLwx4i5V49RXHOozJZq?si=d1acf67ab3db45c0' }
- {name: 'Iron Man revisited',image: 'assets/img/photo9.jpg',soundtrack: 'Shoot to thrill',author: 'AC/DC',spotifyurl: 'https://open.spotify.com/track/0C80GCp0mMuBzLf3EAXqxv?si=dc6a8ce03c474b35' }
- {name: 'You Make me wonna be a better man',image: 'assets/img/photo10.jpg',soundtrack: 'Dog''s Days are over',author: 'Florence + Machine Head',spotifyurl: 'https://open.spotify.com/track/456WNXWhDwYOSf5SpTuqxd?si=6fad98a0ca8c4a32'}
- {name: 'l'altelier des étolies',image: 'assets/img/photo11.webp',soundtrack: 'Don't let me be misunderstood',author: 'Nina Simone',spotifyurl: 'https://open.spotify.com/track/7M9pPyt8Gr41THLhbz4NSB?si=7c230d26996b48f0'}
- {name: 'Tiger',image: 'assets/img/photo12.jpg',soundtrack: 'Eye of the tiger',author: 'Survivor',spotifyurl: 'https://open.spotify.com/track/7M9pPyt8Gr41THLhbz4NSB?si=7c230d26996b48f0'}
- {name: 'Waiting for the sun to set',image: 'assets/img/photo13.jpg',soundtrack: 'He''s fine',author: 'The secret sisters',spotifyurl: 'https://open.spotify.com/track/34iHUnhp0sZXdnpQLP43PI?si=ec6ad6e0ac364915'}
- {name: 'Party in a Vintage shop',image: 'assets/img/photo14.jpg',soundtrack: 'They don''t know you like you do',author: 'Imagine Dragons',spotifyurl: 'https://open.spotify.com/track/7KGwRAF99Ryell3B2T4DKy?si=b699ab007c984d8e'}
- {name: 'image15',image: 'assets/img/photo15.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image16',image: 'assets/img/photo16.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image17',image: 'assets/img/photo17.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image18',image: 'assets/img/photo18.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image19',image: 'assets/img/photo19.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image20',image: 'assets/img/photo20.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image21',image: 'assets/img/photo21.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image22',image: 'assets/img/photo22.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image23',image: 'assets/img/photo23.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image24',image: 'assets/img/photo24.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image25',image: 'assets/img/photo25.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }



social:
- {icon: 'github', link: 'https://github.com/gregoriomarchesini'}
- {icon: 'instagram', link: 'https://www.instagram.com/nowa.y98/?hl=it'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gregoriomarchesini/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=XMflop0AAAAJ&hl=it&oi=ao'}


contacts:
- {name: 'Gregorio ', title: 'Ph.D Candidate', department: 'Decision and Control Systems', institution: 'KTH, Royal Institute of Technology', institution_address: 'Malvinas väg 10, 100 44 , Stockholm', phone: '(+39) 349 642 4427', email: 'gremar@kth.se', office: '', image: 'assets/img/kth_image.jpg'}
