menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'beside research', url: '/bresearch'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}


gallery:
- {name: 'image1',image: 'assets/img/photo1.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image2',image: 'assets/img/photo2.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image3',image: 'assets/img/photo3.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image4',image: 'assets/img/photo4.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image5',image: 'assets/img/photo5.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image6',image: 'assets/img/photo6.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image7',image: 'assets/img/photo7.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image8',image: 'assets/img/photo8.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image9',image: 'assets/img/photo9.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image10',image: 'assets/img/photo10.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image11',image: 'assets/img/photo11.webp',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image12',image: 'assets/img/photo12.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image13,image: 'assets/img/photo10.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image14,image: 'assets/img/photo11.webp',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image15,image: 'assets/img/photo12.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image16,image: 'assets/img/photo10.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image17,image: 'assets/img/photo11.webp',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image18,image: 'assets/img/photo12.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image19,image: 'assets/img/photo10.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image20',image: 'assets/img/photo11.webp',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image21',image: 'assets/img/photo12.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: ''}
- {name: 'image22',image: 'assets/img/photo1.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image23',image: 'assets/img/photo2.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image24',image: 'assets/img/photo3.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }
- {name: 'image25',image: 'assets/img/photo4.jpg',soundtrack: 'to do',author: 'to do',spotifyurl: '' }



social:
- {icon: 'github', link: 'https://github.com/gregoriomarchesini'}
- {icon: 'instagram', link: 'https://www.instagram.com/nowa.y98/?hl=it'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gregoriomarchesini/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=XMflop0AAAAJ&hl=it&oi=ao'}


contacts:
- {name: 'Gregorio ', title: 'Ph.D Candidate', department: 'Decision and Control Systems', institution: 'KTH, Royal Institute of Technology', institution_address: 'Malvinas väg 10, 100 44 , Stockholm', phone: '(+39) 349 642 4427', email: 'gremar@kth.se', office: '', image: 'assets/img/kth_image.jpg'}
